package com.bts.utils;

public enum Type {
	DEVELOPER_REGISTRATION, TESTER_REGISTRATION, DEVELOPER_LIST, TESTER_LIST, PROJECT_LIST, APPROVAL_LIST, TESTER_LOGIN, DEVELOPER_LOGIN,
	WRAPPER_LIST, SAVE_EMPLOYEE_WRAPPER,
	DEVELOPER_HOME, TESTER_HOME, ADMIN_HOME_FETCH_COMPLETED_PROJECTS, ADMIN_HOME_FETCH_LIVE_PROJECTS
}
